version: "3.9"
services:
    db:
        hostname: commandersql
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "sharedDemo!P@ssword"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        ports:
          - "1433:1433"
    gqlapi:
        hostname: commandergql
        image: justinsbits/lab-api-aspnetcore-gql
        build:
            context: ../lab-services
            dockerfile: ../lab-services/lab-api-aspnetcore-gql/Dockerfile
        ports:
            - "5000:80"
        depends_on:
            - db
    restapi:
        hostname: commanderrest
        image: justinsbits/lab-api-aspnetcore-rest
        build:
            context: ../lab-services
            dockerfile: ../lab-services/lab-api-aspnetcore-rest/Dockerfile
        ports:
            - "5010:80"
        depends_on:
            - db
    react:
        hostname: reactui
        image: justinsbits/lab-ui-react
        build:
            context: ../lab-ui/lab-ui-react
        ports:
            - "3001:80"
        depends_on:
            - db
            - gqlapi